### ISSUE TITLE
jhdsa

### ISSUE THREAD

**Issue by Noveel** [Noveel/CFD_Project4#4]
[geometry.pdf](https://github.com/Noveel/CFD_Project4/files/211297/geometry.pdf)

**Comment by salmoh** [comment]
[bc-table.ods.zip](https://github.com/Noveel/CFD_Project4/files/211303/bc-table.ods.zip)

**Comment by Noveel** [comment]
[BC.pdf](https://github.com/Noveel/CFD_Project4/files/211311/BC.pdf)

**Comment by Noveel** [comment]
[PresentationCFD.odp.tar.gz](https://github.com/Noveel/CFD_Project4/files/212760/PresentationCFD.odp.tar.gz)

**Comment by Noveel** [comment]
[PresentationCFD.odp.tar.gz](https://github.com/Noveel/CFD_Project4/files/212867/PresentationCFD.odp.tar.gz)

**Comment by Noveel** [comment]
[PresentationCFD.pdf](https://github.com/Noveel/CFD_Project4/files/214856/PresentationCFD.pdf)
